export const CONFIG = {
    API_URL: '/api',
    WS_RECONNECT_ATTEMPTS: 5,
    WS_RECONNECT_DELAY: 3000,
    MESSAGE_LOAD_LIMIT: 10,
    MESSAGE_SCROLL_THRESHOLD: 50,
    TOAST_DURATION: 3000,
    POST_PREVIEW_LENGTH: 200
};
